from .task1 import main
from .task2 import main
from .task3 import main
from .task4 import main
from .task5 import main
from .task6 import main
from .task7 import main
from .task8 import main
from .task9 import main
